apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nginx-proxy
  #namespace: ... [optional]
  labels:
    app: ingress
spec:
  virtualhost:
    fqdn: ryan-asap.com # Change to a valid Domain name you want
  routes:
  - conditions:
    - prefix: /
    services:
    - name: asap-service
      port: 80
